language: php
sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 7.1

cache:
  directories:
    - $HOME/libsodium
    - vendor

addons:
  apt:
    packages:
    - curl
    - openssl

before_script:
  - composer selfupdate
  - sed -i s#\>=5.4.0#\>=5.3.0#g composer.json
  - ./bin/install-dependencies.sh
  - composer install --prefer-source --no-ansi --no-interaction

script: phpunit

after_script:
  - php vendor/bin/coveralls -v
